# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/lorenzo/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/lorenzo/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lorenzo/map_pilot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lorenzo/map_pilot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/lorenzo/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/lorenzo/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lorenzo/map_pilot/CMakeFiles /home/lorenzo/map_pilot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lorenzo/map_pilot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MapPilot

# Build rule for target.
MapPilot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MapPilot
.PHONY : MapPilot

# fast build rule for target.
MapPilot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/build
.PHONY : MapPilot/fast

src/data_structures/min_heap/min_heap.o: src/data_structures/min_heap/min_heap.cpp.o
.PHONY : src/data_structures/min_heap/min_heap.o

# target to build an object file
src/data_structures/min_heap/min_heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/min_heap/min_heap.cpp.o
.PHONY : src/data_structures/min_heap/min_heap.cpp.o

src/data_structures/min_heap/min_heap.i: src/data_structures/min_heap/min_heap.cpp.i
.PHONY : src/data_structures/min_heap/min_heap.i

# target to preprocess a source file
src/data_structures/min_heap/min_heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/min_heap/min_heap.cpp.i
.PHONY : src/data_structures/min_heap/min_heap.cpp.i

src/data_structures/min_heap/min_heap.s: src/data_structures/min_heap/min_heap.cpp.s
.PHONY : src/data_structures/min_heap/min_heap.s

# target to generate assembly for a file
src/data_structures/min_heap/min_heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/min_heap/min_heap.cpp.s
.PHONY : src/data_structures/min_heap/min_heap.cpp.s

src/data_structures/rtrees/core/rtree_base.o: src/data_structures/rtrees/core/rtree_base.cpp.o
.PHONY : src/data_structures/rtrees/core/rtree_base.o

# target to build an object file
src/data_structures/rtrees/core/rtree_base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/core/rtree_base.cpp.o
.PHONY : src/data_structures/rtrees/core/rtree_base.cpp.o

src/data_structures/rtrees/core/rtree_base.i: src/data_structures/rtrees/core/rtree_base.cpp.i
.PHONY : src/data_structures/rtrees/core/rtree_base.i

# target to preprocess a source file
src/data_structures/rtrees/core/rtree_base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/core/rtree_base.cpp.i
.PHONY : src/data_structures/rtrees/core/rtree_base.cpp.i

src/data_structures/rtrees/core/rtree_base.s: src/data_structures/rtrees/core/rtree_base.cpp.s
.PHONY : src/data_structures/rtrees/core/rtree_base.s

# target to generate assembly for a file
src/data_structures/rtrees/core/rtree_base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/core/rtree_base.cpp.s
.PHONY : src/data_structures/rtrees/core/rtree_base.cpp.s

src/data_structures/rtrees/core/rtree_node.o: src/data_structures/rtrees/core/rtree_node.cpp.o
.PHONY : src/data_structures/rtrees/core/rtree_node.o

# target to build an object file
src/data_structures/rtrees/core/rtree_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/core/rtree_node.cpp.o
.PHONY : src/data_structures/rtrees/core/rtree_node.cpp.o

src/data_structures/rtrees/core/rtree_node.i: src/data_structures/rtrees/core/rtree_node.cpp.i
.PHONY : src/data_structures/rtrees/core/rtree_node.i

# target to preprocess a source file
src/data_structures/rtrees/core/rtree_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/core/rtree_node.cpp.i
.PHONY : src/data_structures/rtrees/core/rtree_node.cpp.i

src/data_structures/rtrees/core/rtree_node.s: src/data_structures/rtrees/core/rtree_node.cpp.s
.PHONY : src/data_structures/rtrees/core/rtree_node.s

# target to generate assembly for a file
src/data_structures/rtrees/core/rtree_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/core/rtree_node.cpp.s
.PHONY : src/data_structures/rtrees/core/rtree_node.cpp.s

src/data_structures/rtrees/rtree/rtree.o: src/data_structures/rtrees/rtree/rtree.cpp.o
.PHONY : src/data_structures/rtrees/rtree/rtree.o

# target to build an object file
src/data_structures/rtrees/rtree/rtree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/rtree/rtree.cpp.o
.PHONY : src/data_structures/rtrees/rtree/rtree.cpp.o

src/data_structures/rtrees/rtree/rtree.i: src/data_structures/rtrees/rtree/rtree.cpp.i
.PHONY : src/data_structures/rtrees/rtree/rtree.i

# target to preprocess a source file
src/data_structures/rtrees/rtree/rtree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/rtree/rtree.cpp.i
.PHONY : src/data_structures/rtrees/rtree/rtree.cpp.i

src/data_structures/rtrees/rtree/rtree.s: src/data_structures/rtrees/rtree/rtree.cpp.s
.PHONY : src/data_structures/rtrees/rtree/rtree.s

# target to generate assembly for a file
src/data_structures/rtrees/rtree/rtree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/data_structures/rtrees/rtree/rtree.cpp.s
.PHONY : src/data_structures/rtrees/rtree/rtree.cpp.s

src/graph/graph.o: src/graph/graph.cpp.o
.PHONY : src/graph/graph.o

# target to build an object file
src/graph/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/graph.cpp.o
.PHONY : src/graph/graph.cpp.o

src/graph/graph.i: src/graph/graph.cpp.i
.PHONY : src/graph/graph.i

# target to preprocess a source file
src/graph/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/graph.cpp.i
.PHONY : src/graph/graph.cpp.i

src/graph/graph.s: src/graph/graph.cpp.s
.PHONY : src/graph/graph.s

# target to generate assembly for a file
src/graph/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/graph.cpp.s
.PHONY : src/graph/graph.cpp.s

src/graph/heuristics.o: src/graph/heuristics.cpp.o
.PHONY : src/graph/heuristics.o

# target to build an object file
src/graph/heuristics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/heuristics.cpp.o
.PHONY : src/graph/heuristics.cpp.o

src/graph/heuristics.i: src/graph/heuristics.cpp.i
.PHONY : src/graph/heuristics.i

# target to preprocess a source file
src/graph/heuristics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/heuristics.cpp.i
.PHONY : src/graph/heuristics.cpp.i

src/graph/heuristics.s: src/graph/heuristics.cpp.s
.PHONY : src/graph/heuristics.s

# target to generate assembly for a file
src/graph/heuristics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/heuristics.cpp.s
.PHONY : src/graph/heuristics.cpp.s

src/graph/highways.o: src/graph/highways.cpp.o
.PHONY : src/graph/highways.o

# target to build an object file
src/graph/highways.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/highways.cpp.o
.PHONY : src/graph/highways.cpp.o

src/graph/highways.i: src/graph/highways.cpp.i
.PHONY : src/graph/highways.i

# target to preprocess a source file
src/graph/highways.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/highways.cpp.i
.PHONY : src/graph/highways.cpp.i

src/graph/highways.s: src/graph/highways.cpp.s
.PHONY : src/graph/highways.s

# target to generate assembly for a file
src/graph/highways.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/graph/highways.cpp.s
.PHONY : src/graph/highways.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/utm_converter.o: src/utils/utm_converter.cpp.o
.PHONY : src/utils/utm_converter.o

# target to build an object file
src/utils/utm_converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/utils/utm_converter.cpp.o
.PHONY : src/utils/utm_converter.cpp.o

src/utils/utm_converter.i: src/utils/utm_converter.cpp.i
.PHONY : src/utils/utm_converter.i

# target to preprocess a source file
src/utils/utm_converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/utils/utm_converter.cpp.i
.PHONY : src/utils/utm_converter.cpp.i

src/utils/utm_converter.s: src/utils/utm_converter.cpp.s
.PHONY : src/utils/utm_converter.s

# target to generate assembly for a file
src/utils/utm_converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapPilot.dir/build.make CMakeFiles/MapPilot.dir/src/utils/utm_converter.cpp.s
.PHONY : src/utils/utm_converter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MapPilot"
	@echo "... src/data_structures/min_heap/min_heap.o"
	@echo "... src/data_structures/min_heap/min_heap.i"
	@echo "... src/data_structures/min_heap/min_heap.s"
	@echo "... src/data_structures/rtrees/core/rtree_base.o"
	@echo "... src/data_structures/rtrees/core/rtree_base.i"
	@echo "... src/data_structures/rtrees/core/rtree_base.s"
	@echo "... src/data_structures/rtrees/core/rtree_node.o"
	@echo "... src/data_structures/rtrees/core/rtree_node.i"
	@echo "... src/data_structures/rtrees/core/rtree_node.s"
	@echo "... src/data_structures/rtrees/rtree/rtree.o"
	@echo "... src/data_structures/rtrees/rtree/rtree.i"
	@echo "... src/data_structures/rtrees/rtree/rtree.s"
	@echo "... src/graph/graph.o"
	@echo "... src/graph/graph.i"
	@echo "... src/graph/graph.s"
	@echo "... src/graph/heuristics.o"
	@echo "... src/graph/heuristics.i"
	@echo "... src/graph/heuristics.s"
	@echo "... src/graph/highways.o"
	@echo "... src/graph/highways.i"
	@echo "... src/graph/highways.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/utm_converter.o"
	@echo "... src/utils/utm_converter.i"
	@echo "... src/utils/utm_converter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

